baseURL = 'https://abdelkassar.com/'
languageCode = 'en-us'
title = "Yassin"
theme = "hugo-texify3"

[params]
	author = "Yassin Abdelkassar"
	description = "My new blog"
	enable_math = true

[params.social]
	github = "yassinkassar"
	linkedin = "yassin-abdelkassar"